#!/usr/bin/env zsh

# Opens the {pull request,merge request} on git{hub,lab} for the current project & branch

git_url=$(git remote show -n origin | awk '$0 ~ /^ +Fetch URL/ { print $3 }')
git_host=$(echo $git_url | sed -Ee 's#^.*@(.+):.*$#\1#')
git_repo=$(echo $git_url | sed -Ee 's#^.+[/:]([^/]+/[^/]+)$#\1#')
git_branch=$(git current-branch)

case $git_host in
gitlab.com)
  url_path="/merge_requests/new?merge_request%5Bsource_branch%5D=${git_branch}"
  ;;
*)
  url_path="/pull/${git_branch}"
  ;;
esac

open "https://${git_host}/${git_repo}/${url_path}"
