#!/usr/bin/env ruby
#
# Opens ../<current folder name>.tmproj
#

home = File.expand_path("~")
if [
    "/",
    home,
    "#{home}/sources",
    "#{home}/freeagent",
    "#{home}/freeagent/src",
  ].include? Dir.pwd
  puts "Not opening #{Dir.pwd.inspect} in mate"
  exit(1)
end

`mate .`
